fix: debug workflow

diff --git a/.github/workflows/release-debug-version.yml b/.github/workflows/release-debug-version.yml
--- a/.github/workflows/release-debug-version.yml
+++ b/.github/workflows/release-debug-version.yml
@@ -7,51 +7,55 @@ on:
       - "v[0-9]+.[0-9]+.[0-9]+-dev"
 
 env:
-  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output\
-  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
   GITHUB_PACKAGES_URL: 'https://nuget.pkg.github.com/asv-soft/index.json'
-  PROJECT_NAME: 'Asv.Ulog'
+  PROJECT_NAME: 'Asv.ULog'
   PROPS_VERSION_VAR_NAME: 'ProductVersion'
 
 jobs:
-  deploy:
-    name: 'Deploy'
-    runs-on: windows-2019
+  build:
+    runs-on: ubuntu-latest
     if: startsWith(github.ref, 'refs/tags/v')
     steps:
-      - name: 'Checkout'
+      - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Setup .Net
-        uses: actions/setup-dotnet@v3
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v1
         with:
-          dotnet-version: |
-            8.x.x
+          dotnet-version: '8.0.x'
 
-      - name: Get version
-        id: version
-        uses: battila7/get-version-action@v2
+      - name: Add NuGet source
+        run: dotnet nuget add source ${{ env.GITHUB_PACKAGES_URL }} \--username '${{secrets.USER_NAME}}' \--password '${{secrets.GIHUB_NUGET_AUTH_TOKEN}}' \--store-password-in-clear-text
 
-      - name: Check version
-        run: echo ${{ steps.version.outputs.version-without-v }}
-
-      - name: Add github as NuGet source
-        run: |
-          dotnet nuget add source ${{ env.GITHUB_PACKAGES_URL }} --username '${{ secrets.USER_NAME }}' --password '${{ secrets.GIHUB_NUGET_AUTH_TOKEN }}' --store-password-in-clear-text
-
-      - name: Restore dependencies
+      - name: Install dependencies
         run: dotnet restore ./src/${{env.PROJECT_NAME}}/${{env.PROJECT_NAME}}.csproj
 
       - name: Build
         run: dotnet build ./src/${{env.PROJECT_NAME}}/${{env.PROJECT_NAME}}.csproj --configuration Release --no-restore
+        
+      - name: Running Tests
+        run: dotnet test ./src/${{env.PROJECT_NAME}}.Tests/${{env.PROJECT_NAME}}.Tests.csproj --verbosity normal
 
-      - name: Running all tests
-        run:  |
-          cd src
-          dotnet test --no-restore --verbosity normal
+      - name: Set version variable
+        env:
+          TAG: ${{ github.ref_name }}
+        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
 
-      - name: Pack project
+      - name: Read version from Directory.Build.props
+        id: read-version
         run: |
-          cd src
-          dotnet pack -c Release --no-build --no-restore -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
+          version=$(grep -oP '<${{env.PROPS_VERSION_VAR_NAME}}>\K[^<]+' ./src/Directory.Build.props)
+          echo "PropsVersion=${version}" >> $GITHUB_ENV
 
+      - name: Compare tag with NuGet package version
+        run: |
+          if [ "${{ env.PropsVersion }}" != "${{ env.VERSION }}" ]; then
+            echo "Error: Tag does not match NuGet package version"
+            exit 1
+          fi
+
+      - name: Pack package
+        run: dotnet pack ./src/${{env.PROJECT_NAME}}/${{env.PROJECT_NAME}}.csproj -c Release /p:Version=${{ env.VERSION }} --no-build -o .
+
+      - name: List output files
+        run: ls -la
